// AUTO-GENERATED from the CutPilot Premiere plugin's caption preset catalog
// (vikasbanjare/video · CutPilot/js/captions.js). Do not edit by hand — these
// are the exact template definitions ported into the web engine.

export interface RawTemplate {
  id: string;
  name: string;
  category: string;
  popularity?: number;
  layout?: "top" | "center" | "bottom";
  keyword?: boolean;
  speaker?: boolean;
  font: string;
  fallbackFonts?: string[];
  fontSize: number;
  weight?: number;
  uppercase?: boolean;
  wordsPerCue?: number;
  maxLines?: number;
  letterSpacing?: number;
  anim?: string;
  highlightScale?: number;
  upcomingOpacity?: number;
  fill?: string;
  fill2?: string;
  glossy?: boolean;
  stroke?: string | null;
  strokeWidth?: number;
  glow?: string | null;
  glowBlur?: number;
  highlight?: string | null;
  highlight2?: string;
  highlightStyle?: "color" | "box" | "bar";
  highlightFont?: string;
  highlightItalic?: boolean;
  boxColor?: string | null;
  boxColor2?: string;
  boxGradient?: "v" | "h";
  boxStops?: Array<[number, string]>;
  boxOpacity?: number;
  boxRadius?: number;
  boxPad?: number;
  boxStroke?: string;
  boxStrokeWidth?: number;
  boxGlow?: string;
  boxGlowBlur?: number;
  box3d?: string;
  box3dDepth?: number;
  boxGloss?: number;
  boxShadow?: string;
  boxShadowBlur?: number;
  boxShadowDY?: number;
  shadowDX?: number;
  shadowDY?: number;
}

export const RAW_TEMPLATES: RawTemplate[] = [
  {"id":"hormozi","name":"Bold Statement","category":"Bold Creator","popularity":99,"layout":"bottom","keyword":true,"font":"Montserrat","fallbackFonts":["Anton","Bebas Neue","Arial Black"],"fontSize":90,"weight":900,"uppercase":true,"wordsPerCue":1,"anim":"pop-scale","highlightScale":1.14,"fill":"#FFFFFF","stroke":"#000000","strokeWidth":12,"highlight":"#FFD400"},
  {"id":"karaoke","name":"Karaoke Highlight","category":"Dynamic Highlight","popularity":95,"layout":"bottom","keyword":false,"font":"Poppins","fallbackFonts":["Inter","Arial"],"fontSize":70,"weight":600,"uppercase":false,"wordsPerCue":3,"anim":"color-sweep","fill":"#FFFFFF","stroke":"#000000","strokeWidth":8,"highlight":"#00E676"},
  {"id":"highlight-box","name":"Highlight Box","category":"Social Growth","popularity":92,"layout":"bottom","keyword":true,"font":"Inter","fallbackFonts":["Helvetica","Arial"],"fontSize":64,"weight":700,"uppercase":false,"wordsPerCue":3,"anim":"box-snap","fill":"#FFFFFF","stroke":"#000000","strokeWidth":6,"highlight":"#FF3B6B","highlightStyle":"box","boxRadius":14},
  {"id":"minimal","name":"Clean Minimal","category":"Minimal Professional","popularity":80,"layout":"bottom","keyword":false,"font":"Inter","fallbackFonts":["Helvetica Neue","Arial"],"fontSize":48,"weight":500,"uppercase":false,"wordsPerCue":0,"anim":"fade","fill":"#FFFFFF","stroke":"#000000","strokeWidth":3,"highlight":null},
  {"id":"neon","name":"Neon Pop","category":"Gaming Stream","popularity":88,"layout":"center","keyword":true,"font":"Bebas Neue","fallbackFonts":["Anton","Impact"],"fontSize":80,"uppercase":true,"wordsPerCue":1,"anim":"glitch-in","fill":"#F8F8FF","stroke":"#7B2FFF","strokeWidth":6,"glow":"#00F0FF","highlight":"#00F0FF"},
  {"id":"typewriter","name":"Typewriter","category":"Storytelling","popularity":70,"layout":"center","keyword":false,"font":"JetBrains Mono","fallbackFonts":["Courier New"],"fontSize":54,"uppercase":false,"wordsPerCue":0,"anim":"typewriter","fill":"#EAEAEA","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":null},
  {"id":"boldyellow","name":"Bold Yellow","category":"Motivation","popularity":90,"layout":"bottom","keyword":true,"font":"Anton","fallbackFonts":["Bebas Neue","Impact","Arial Black"],"fontSize":88,"uppercase":true,"wordsPerCue":1,"anim":"pop-scale","highlightScale":1.14,"fill":"#FFD400","stroke":"#000000","strokeWidth":12,"highlight":"#FFFFFF"},
  {"id":"cleanwhite","name":"Clean White","category":"Minimal Professional","popularity":78,"layout":"bottom","keyword":false,"font":"Poppins","fallbackFonts":["Inter","Helvetica","Arial"],"fontSize":64,"weight":600,"uppercase":false,"wordsPerCue":2,"anim":"fade","fill":"#FFFFFF","stroke":"#000000","strokeWidth":5,"highlight":"#FFD400"},
  {"id":"tvnews","name":"News Bar","category":"Podcast Pro","popularity":65,"layout":"bottom","keyword":false,"speaker":true,"font":"Inter","fallbackFonts":["Helvetica Neue","Arial"],"fontSize":46,"weight":500,"uppercase":false,"wordsPerCue":0,"anim":"fade","fill":"#FFFFFF","stroke":null,"strokeWidth":0,"highlight":"#33C1FF","boxColor":"#000000","boxRadius":6},
  {"id":"pro-spotlight","name":"Spotlight","category":"⭐ Premium","popularity":100,"layout":"bottom","keyword":false,"font":"Montserrat","fallbackFonts":["Poppins","Inter","Arial"],"fontSize":62,"uppercase":false,"wordsPerCue":4,"anim":"karaoke","highlightScale":1.1,"fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#2D7CFF","highlightStyle":"box","boxRadius":12},
  {"id":"pro-subs-light","name":"Subs Light","category":"⭐ Premium","popularity":100,"layout":"bottom","keyword":false,"font":"Montserrat","fallbackFonts":["Poppins","Inter","Arial"],"fontSize":58,"uppercase":false,"wordsPerCue":3,"anim":"karaoke","highlightScale":1,"upcomingOpacity":0.4,"fill":"#15181E","stroke":null,"strokeWidth":0,"glow":null,"highlight":"#2D7CFF","highlightStyle":"color","boxColor":"#F1F2F4","boxOpacity":1,"boxRadius":16},
  {"id":"pro-clean-glow","name":"Clean Glow","category":"⭐ Premium","popularity":99,"layout":"center","keyword":false,"font":"Montserrat","fallbackFonts":["Poppins","Inter","Arial Black"],"fontSize":64,"uppercase":false,"wordsPerCue":3,"anim":"karaoke","highlightScale":1.12,"upcomingOpacity":0.55,"fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":"#000000","glowBlur":0.5,"highlight":"#FFFFFF","highlightStyle":"color","boxColor":null},
  {"id":"pro-karaokebar","name":"Karaoke Bar","category":"⭐ Premium","popularity":99,"layout":"bottom","keyword":false,"font":"Montserrat","fallbackFonts":["Poppins","Inter","Arial"],"fontSize":54,"weight":800,"uppercase":false,"wordsPerCue":5,"anim":"karaoke","highlightScale":1,"fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":null,"highlight":"#F5A623","highlightStyle":"box","boxColor":"#0C0D11","boxOpacity":0.72,"boxRadius":9,"boxPad":1.15},
  {"id":"pro-pulse","name":"Pulse","category":"⭐ Premium","popularity":99,"layout":"center","keyword":true,"font":"Montserrat","fallbackFonts":["Poppins","Arial Black"],"fontSize":66,"uppercase":true,"wordsPerCue":3,"anim":"reveal","highlightScale":1.1,"fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#3B5BFF","highlightStyle":"box","boxRadius":10},
  {"id":"pro-thuban","name":"Thuban","category":"⭐ Premium","popularity":98,"layout":"bottom","keyword":true,"font":"Montserrat","fallbackFonts":["Poppins","Arial Black"],"fontSize":62,"uppercase":true,"wordsPerCue":3,"anim":"reveal","highlightScale":1.1,"fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#FFE000","highlightStyle":"box","boxRadius":10},
  {"id":"pro-runway","name":"Runway","category":"⭐ Premium","popularity":97,"layout":"bottom","keyword":true,"font":"Poppins","fallbackFonts":["Montserrat","Inter","Arial"],"fontSize":58,"uppercase":false,"wordsPerCue":3,"anim":"reveal","highlightScale":1.1,"fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#FF2D9B","highlightStyle":"box","boxRadius":14},
  {"id":"pro-copernicus","name":"Copernicus","category":"⭐ Premium","popularity":96,"layout":"bottom","keyword":true,"font":"Montserrat","fallbackFonts":["Poppins","Arial Black"],"fontSize":62,"uppercase":true,"wordsPerCue":3,"anim":"reveal","highlightScale":1.1,"fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#15C47E","highlightStyle":"box","boxRadius":10},
  {"id":"pro-clarity","name":"Clarity","category":"⭐ Premium","popularity":95,"layout":"center","keyword":false,"font":"Inter","fallbackFonts":["Helvetica Neue","Arial"],"fontSize":54,"uppercase":false,"wordsPerCue":4,"anim":"fade","fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#FFFFFF"},
  {"id":"pro-evo","name":"Evo","category":"⭐ Premium","popularity":94,"layout":"bottom","keyword":true,"font":"Poppins","fallbackFonts":["Inter","Arial"],"fontSize":60,"uppercase":false,"wordsPerCue":4,"anim":"reveal","highlightScale":1.1,"fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#FFD400"},
  {"id":"pro-nova","name":"Nova","category":"⭐ Premium","popularity":93,"layout":"bottom","keyword":true,"font":"Montserrat","fallbackFonts":["Poppins","Arial Black"],"fontSize":64,"uppercase":true,"wordsPerCue":3,"anim":"reveal","highlightScale":1.1,"fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#FF3B6B"},
  {"id":"pro-andromeda","name":"Andromeda","category":"⭐ Premium","popularity":92,"layout":"bottom","keyword":false,"font":"Outfit","fallbackFonts":["Inter","Arial"],"fontSize":46,"uppercase":false,"wordsPerCue":0,"anim":"slide","fill":"#FFFFFF","stroke":null,"strokeWidth":0,"highlight":"#9FE7FF","boxColor":"#10131A","boxRadius":16},
  {"id":"pro-elevate","name":"Elevate","category":"⭐ Premium","popularity":91,"layout":"center","keyword":false,"font":"Playfair Display","fallbackFonts":["Lora","Georgia","serif"],"fontSize":60,"uppercase":false,"wordsPerCue":4,"letterSpacing":0.5,"anim":"fade","fill":"#F6F2EC","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#E8C77A"},
  {"id":"pro-quint","name":"Quintessence","category":"⭐ Premium","popularity":90,"layout":"center","keyword":false,"font":"Playfair Display","fallbackFonts":["Lora","Georgia","serif"],"fontSize":66,"uppercase":false,"wordsPerCue":3,"anim":"scale","fill":"#F3E9D2","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#D9B36A"},
  {"id":"pro-velocity","name":"Velocity","category":"⭐ Premium","popularity":89,"layout":"bottom","keyword":true,"font":"Montserrat","fallbackFonts":["Archivo Black","Arial Black"],"fontSize":78,"uppercase":true,"wordsPerCue":1,"anim":"pop-scale","highlightScale":1.12,"fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#2D7CFF"},
  {"id":"pro-neon","name":"Neon","category":"⭐ Premium","popularity":88,"layout":"center","keyword":true,"font":"Bebas Neue","fallbackFonts":["Anton","Impact"],"fontSize":84,"uppercase":true,"wordsPerCue":1,"anim":"glitch-in","fill":"#FFFFFF","stroke":"#0A0A0A","strokeWidth":3,"glow":"#22D3FF","highlight":"#FF2D9B"},
  {"id":"v1-hormozi26","name":"Statement Pro","category":"⭐ Premium","popularity":87,"layout":"bottom","keyword":true,"font":"Montserrat","fallbackFonts":["Archivo Black","Arial Black"],"fontSize":72,"uppercase":true,"wordsPerCue":3,"anim":"reveal","highlightScale":1.12,"fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#FFE000","highlightStyle":"box","boxRadius":10},
  {"id":"v1-finance","name":"Finance Pro","category":"⭐ Premium","popularity":86,"layout":"bottom","keyword":true,"font":"Montserrat","fallbackFonts":["Inter","Arial"],"fontSize":60,"uppercase":false,"wordsPerCue":4,"anim":"reveal","highlightScale":1.1,"fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#16C784","highlightStyle":"box","boxRadius":10},
  {"id":"v1-podcast","name":"Podcast Pro","category":"⭐ Premium","popularity":85,"layout":"bottom","keyword":false,"speaker":true,"font":"Inter","fallbackFonts":["Helvetica Neue","Arial"],"fontSize":48,"uppercase":false,"wordsPerCue":0,"anim":"slide","fill":"#FFFFFF","stroke":null,"strokeWidth":0,"highlight":"#5CC8FF","boxColor":"#10131A","boxRadius":14},
  {"id":"v1-reels","name":"Indian Reels","category":"⭐ Premium","popularity":84,"layout":"bottom","keyword":true,"font":"Poppins","fallbackFonts":["Montserrat","Inter","Arial"],"fontSize":62,"uppercase":false,"wordsPerCue":3,"anim":"reveal","highlightScale":1.12,"fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#FF2D9B","highlightStyle":"box","boxRadius":14},
  {"id":"v1-beast","name":"MrBeast Inspired","category":"⭐ Premium","popularity":83,"layout":"bottom","keyword":true,"font":"Archivo Black","fallbackFonts":["Montserrat","Arial Black"],"fontSize":78,"uppercase":true,"wordsPerCue":1,"anim":"pop-scale","highlightScale":1.18,"fill":"#FFFFFF","stroke":"#000000","strokeWidth":4,"glow":"#000000","highlight":"#FF2A2A"},
  {"id":"v1-ali","name":"Ali Abdaal Inspired","category":"⭐ Premium","popularity":82,"layout":"bottom","keyword":false,"font":"Inter","fallbackFonts":["Helvetica Neue","Arial"],"fontSize":50,"uppercase":false,"wordsPerCue":4,"anim":"fade","fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#FFFFFF"},
  {"id":"impact","name":"Impact II","category":"Bold Creator","popularity":97,"layout":"bottom","keyword":true,"font":"Anton","fallbackFonts":["Bebas Neue","Impact","Arial Black"],"fontSize":92,"uppercase":true,"wordsPerCue":1,"anim":"pop","highlightScale":1.18,"fill":"#FFFFFF","stroke":"#000000","strokeWidth":13,"highlight":"#FFE53B"},
  {"id":"prime","name":"Prime","category":"Bold Creator","popularity":94,"layout":"center","keyword":true,"font":"Archivo Black","fallbackFonts":["Montserrat","Arial Black"],"fontSize":86,"uppercase":true,"wordsPerCue":2,"anim":"zoom","fill":"#FFFFFF","stroke":"#000000","strokeWidth":10,"highlight":"#7C5CFF"},
  {"id":"byline","name":"Byline","category":"Minimal Professional","popularity":82,"layout":"bottom","keyword":false,"font":"Inter","fallbackFonts":["Helvetica Neue","Arial"],"fontSize":50,"uppercase":false,"wordsPerCue":0,"anim":"fade","fill":"#FFFFFF","stroke":"#000000","strokeWidth":3,"highlight":"#9AD0FF"},
  {"id":"magazine","name":"Magazine","category":"Minimal Professional","popularity":74,"layout":"center","keyword":false,"font":"Georgia","fallbackFonts":["Times New Roman","serif"],"fontSize":58,"uppercase":false,"wordsPerCue":0,"letterSpacing":1,"anim":"fade","fill":"#F5F1E8","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#D9B36A"},
  {"id":"focus","name":"Focus","category":"Dynamic Highlight","popularity":93,"layout":"bottom","keyword":true,"font":"Poppins","fallbackFonts":["Inter","Arial"],"fontSize":66,"uppercase":false,"wordsPerCue":3,"anim":"karaoke","fill":"#FFFFFF","stroke":"#000000","strokeWidth":6,"highlight":"#FF3B6B","highlightStyle":"box","boxRadius":14},
  {"id":"volt","name":"Volt","category":"Dynamic Highlight","popularity":91,"layout":"bottom","keyword":true,"font":"Bebas Neue","fallbackFonts":["Anton","Impact"],"fontSize":82,"uppercase":true,"wordsPerCue":3,"anim":"pop","fill":"#FFFFFF","stroke":"#000000","strokeWidth":8,"highlight":"#39FF14"},
  {"id":"rocket","name":"Rocket","category":"Social Growth","popularity":90,"layout":"bottom","keyword":true,"font":"Montserrat","fallbackFonts":["Inter","Arial Black"],"fontSize":70,"uppercase":true,"wordsPerCue":3,"anim":"karaoke","fill":"#FFFFFF","stroke":"#000000","strokeWidth":7,"highlight":"#FF2D7E","highlightStyle":"box","boxRadius":16},
  {"id":"mars","name":"Mars","category":"Social Growth","popularity":87,"layout":"bottom","keyword":true,"font":"Inter","fallbackFonts":["Helvetica","Arial"],"fontSize":64,"uppercase":false,"wordsPerCue":2,"anim":"pop","fill":"#111111","stroke":null,"strokeWidth":0,"highlight":"#111111","boxColor":"#FFE53B","boxRadius":10},
  {"id":"lift","name":"Lift","category":"Podcast Pro","popularity":76,"layout":"bottom","keyword":false,"speaker":true,"font":"Inter","fallbackFonts":["Helvetica Neue","Arial"],"fontSize":52,"uppercase":false,"wordsPerCue":0,"anim":"slide","fill":"#FFFFFF","stroke":"#000000","strokeWidth":4,"highlight":"#5CC8FF"},
  {"id":"lumen","name":"Lumen","category":"Storytelling","popularity":72,"layout":"center","keyword":false,"font":"Georgia","fallbackFonts":["Times New Roman","serif"],"fontSize":56,"uppercase":false,"wordsPerCue":0,"anim":"fade","fill":"#F3EEE6","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#E0C189"},
  {"id":"ember","name":"Ember","category":"Storytelling","popularity":68,"layout":"center","keyword":false,"font":"Georgia","fallbackFonts":["serif"],"fontSize":54,"uppercase":false,"wordsPerCue":0,"anim":"fade","fill":"#FFE9D6","stroke":"#1a1a1a","strokeWidth":2,"highlight":"#FF9E5A"},
  {"id":"rebel","name":"Rebel","category":"Gaming Stream","popularity":85,"layout":"center","keyword":true,"font":"Bebas Neue","fallbackFonts":["Anton","Impact"],"fontSize":84,"uppercase":true,"wordsPerCue":1,"anim":"shake","fill":"#C6FF00","stroke":"#000000","strokeWidth":9,"glow":"#C6FF00","highlight":"#FFFFFF"},
  {"id":"cinema","name":"Cinematic","category":"Cinematic","popularity":79,"layout":"bottom","keyword":false,"font":"Futura","fallbackFonts":["Oswald","Helvetica"],"fontSize":44,"uppercase":true,"wordsPerCue":0,"letterSpacing":4,"anim":"fade","fill":"#EDEDED","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#EDEDED"},
  {"id":"align","name":"Align","category":"Cinematic","popularity":71,"layout":"center","keyword":false,"font":"JetBrains Mono","fallbackFonts":["Courier New","monospace"],"fontSize":40,"uppercase":true,"wordsPerCue":0,"letterSpacing":6,"anim":"fade","fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#9AD0FF"},
  {"id":"grind","name":"Grind","category":"Motivation","popularity":89,"layout":"bottom","keyword":true,"font":"Anton","fallbackFonts":["Bebas Neue","Impact"],"fontSize":90,"uppercase":true,"wordsPerCue":1,"anim":"scale","highlightScale":1.16,"fill":"#FFFFFF","stroke":"#000000","strokeWidth":12,"highlight":"#FFD400"},
  {"id":"chalk","name":"Chalk","category":"Education","popularity":73,"layout":"bottom","keyword":true,"font":"Bradley Hand","fallbackFonts":["Comic Sans MS","cursive"],"fontSize":64,"uppercase":false,"wordsPerCue":2,"anim":"wave","fill":"#FFFFFF","stroke":"#000000","strokeWidth":5,"highlight":"#FFE53B"},
  {"id":"paper","name":"Paper II","category":"Education","popularity":75,"layout":"bottom","keyword":true,"font":"Inter","fallbackFonts":["Helvetica","Arial"],"fontSize":58,"uppercase":false,"wordsPerCue":2,"anim":"pop","fill":"#1A1A1A","stroke":null,"strokeWidth":0,"highlight":"#1A1A1A","boxColor":"#FFFFFF","boxRadius":8},
  {"id":"prism","name":"Prism Pro","category":"Bold Creator","popularity":96,"layout":"bottom","keyword":true,"font":"Montserrat","fallbackFonts":["Inter","Arial Black"],"fontSize":74,"uppercase":false,"wordsPerCue":0,"anim":"pop","fill":"#FFFFFF","stroke":"#000000","strokeWidth":7,"highlight":"#FFD400"},
  {"id":"evo","name":"Evo","category":"Bold Creator","popularity":88,"layout":"bottom","keyword":true,"font":"Poppins","fallbackFonts":["Inter","Arial"],"fontSize":66,"uppercase":false,"wordsPerCue":0,"anim":"pop","highlightScale":1.1,"fill":"#FFFFFF","stroke":"#000000","strokeWidth":5,"highlight":"#FFD400"},
  {"id":"stack","name":"Stack","category":"Bold Creator","popularity":84,"layout":"bottom","keyword":true,"font":"Inter","fallbackFonts":["Helvetica","Arial"],"fontSize":60,"uppercase":false,"wordsPerCue":0,"anim":"fade","fill":"#FFFFFF","stroke":"#000000","strokeWidth":4,"highlight":"#FF4D6D"},
  {"id":"kai","name":"Kai","category":"Social Growth","popularity":86,"layout":"bottom","keyword":false,"font":"Archivo Black","fallbackFonts":["Montserrat","Arial Black"],"fontSize":80,"uppercase":true,"wordsPerCue":1,"anim":"pop","fill":"#FF2D9B","stroke":"#000000","strokeWidth":8,"highlight":"#FFFFFF"},
  {"id":"y2k","name":"Y2K","category":"Gaming Stream","popularity":81,"layout":"center","keyword":false,"font":"Verdana","fallbackFonts":["Tahoma","Arial"],"fontSize":54,"uppercase":false,"wordsPerCue":0,"letterSpacing":1,"anim":"glitch","fill":"#FFFFFF","stroke":null,"strokeWidth":0,"highlight":"#00F0FF","boxColor":"#141414","boxRadius":4},
  {"id":"elevate","name":"Cinema","category":"Cinematic","popularity":77,"layout":"center","keyword":false,"font":"Georgia","fallbackFonts":["Times New Roman","serif"],"fontSize":60,"uppercase":false,"wordsPerCue":0,"letterSpacing":1,"anim":"fade","fill":"#F3ECE0","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#D9B36A"},
  {"id":"sketch","name":"Sketch","category":"Storytelling","popularity":74,"layout":"center","keyword":false,"font":"Bradley Hand","fallbackFonts":["Comic Sans MS","cursive"],"fontSize":64,"uppercase":false,"wordsPerCue":0,"anim":"fade","fill":"#FFFFFF","stroke":"#000000","strokeWidth":4,"highlight":"#FFE53B"},
  {"id":"bloom","name":"Bloom","category":"Storytelling","popularity":71,"layout":"center","keyword":false,"font":"Georgia","fallbackFonts":["serif"],"fontSize":58,"uppercase":false,"wordsPerCue":0,"letterSpacing":1,"anim":"fade","fill":"#FFF3E9","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#E6A0B0"},
  {"id":"linen","name":"Linen","category":"Minimal Professional","popularity":73,"layout":"bottom","keyword":false,"font":"Georgia","fallbackFonts":["Times New Roman","serif"],"fontSize":54,"uppercase":false,"wordsPerCue":0,"letterSpacing":1,"anim":"fade","fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#C9A36A"},
  {"id":"sonnet","name":"Sonnet","category":"Storytelling","popularity":67,"layout":"center","keyword":false,"font":"Georgia","fallbackFonts":["Times New Roman","serif"],"fontSize":48,"uppercase":false,"wordsPerCue":0,"letterSpacing":1,"anim":"fade","fill":"#EFE8DF","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#CBB68B"},
  {"id":"monolith","name":"Monolith","category":"Cinematic","popularity":83,"layout":"center","keyword":false,"font":"Playfair Display","fallbackFonts":["Georgia","Times New Roman","serif"],"fontSize":78,"uppercase":true,"wordsPerCue":2,"letterSpacing":1,"anim":"scale","fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":"#000000","highlight":"#FFFFFF"},
  {"id":"quotepill","name":"Quote Pill","category":"Cinematic","popularity":81,"layout":"center","keyword":false,"font":"Playfair Display","fallbackFonts":["Georgia","Times New Roman","serif"],"fontSize":62,"uppercase":true,"wordsPerCue":3,"letterSpacing":1,"anim":"fade","fill":"#FFFFFF","stroke":null,"strokeWidth":0,"highlight":"#FFFFFF","boxColor":"#0B1020","boxRadius":46},
  {"id":"cap-core","name":"Core","category":"Trending","popularity":99,"layout":"center","keyword":false,"font":"Montserrat","fallbackFonts":["Poppins","Inter","Arial"],"fontSize":68,"uppercase":false,"wordsPerCue":3,"anim":"karaoke","highlightScale":1.14,"fill":"#FFFFFF","stroke":"#000000","strokeWidth":6,"highlight":"#FFE000"},
  {"id":"cap-clarity","name":"Crisp","category":"Trending","popularity":92,"layout":"center","keyword":false,"font":"Inter","fallbackFonts":["Helvetica","Arial"],"fontSize":56,"uppercase":false,"wordsPerCue":4,"anim":"fade","fill":"#FFFFFF","stroke":"#000000","strokeWidth":4,"highlight":"#FFFFFF"},
  {"id":"cap-grit","name":"Grit","category":"Trending","popularity":96,"layout":"center","keyword":false,"font":"Anton","fallbackFonts":["Bebas Neue","Impact","Arial Black"],"fontSize":86,"uppercase":true,"wordsPerCue":3,"anim":"karaoke","highlightScale":1.16,"fill":"#FFFFFF","stroke":"#000000","strokeWidth":11,"highlight":"#FFD400"},
  {"id":"cap-hype","name":"Surge","category":"Trending","popularity":95,"layout":"center","keyword":false,"font":"Montserrat","fallbackFonts":["Poppins","Arial Black"],"fontSize":70,"uppercase":true,"wordsPerCue":3,"anim":"karaoke","fill":"#FFFFFF","stroke":"#000000","strokeWidth":6,"highlight":"#22C55E","highlightStyle":"box","boxRadius":16},
  {"id":"cap-aurora","name":"Aurora","category":"Cinematic","popularity":96,"layout":"center","keyword":false,"font":"Outfit","fallbackFonts":["Poppins","Inter","Arial"],"fontSize":64,"uppercase":false,"wordsPerCue":3,"anim":"karaoke","highlightScale":1.12,"upcomingOpacity":0.55,"fill":"#FFFFFF","fill2":"#B9C7FF","stroke":null,"strokeWidth":0,"glow":"#0A1030","glowBlur":0.5,"highlight":"#7FE7FF","highlightStyle":"color","boxColor":null},
  {"id":"cap-motiv","name":"Hype","category":"Motivation","popularity":95,"layout":"center","keyword":false,"font":"Bangers","fallbackFonts":["Luckiest Guy","Anton","Impact"],"fontSize":96,"uppercase":true,"wordsPerCue":3,"anim":"karaoke","highlightScale":1.2,"fill":"#FFE53B","stroke":"#000000","strokeWidth":13,"glow":null,"highlight":"#FFFFFF","highlightStyle":"color","boxColor":null},
  {"id":"cap-mono","name":"Mono","category":"Gaming Stream","popularity":91,"layout":"bottom","keyword":false,"font":"JetBrains Mono","fallbackFonts":["Roboto Mono","Space Mono","Courier New"],"fontSize":46,"uppercase":false,"wordsPerCue":4,"anim":"karaoke","highlightScale":1.05,"upcomingOpacity":0.5,"fill":"#E6FBFF","stroke":null,"strokeWidth":0,"glow":null,"highlight":"#00F0FF","highlightStyle":"color","boxColor":"#0B1118","boxOpacity":0.92,"boxRadius":8},
  {"id":"cap-pastel","name":"Pastel","category":"Social Growth","popularity":92,"layout":"bottom","keyword":false,"font":"Nunito","fallbackFonts":["Poppins","Inter","Arial"],"fontSize":56,"uppercase":false,"wordsPerCue":3,"anim":"karaoke","highlightScale":1.08,"upcomingOpacity":0.5,"fill":"#2A2233","stroke":null,"strokeWidth":0,"glow":null,"highlight":"#FF5DA2","highlightStyle":"box","boxColor":"#FFFFFF","boxOpacity":1,"boxRadius":24},
  {"id":"cap-editorial","name":"Column","category":"Storytelling","popularity":90,"layout":"center","keyword":false,"font":"Playfair Display","fallbackFonts":["Georgia","Merriweather","Times New Roman"],"fontSize":60,"uppercase":false,"wordsPerCue":4,"anim":"karaoke","highlightScale":1.06,"upcomingOpacity":0.6,"fill":"#F6F2EA","stroke":null,"strokeWidth":0,"glow":"#000000","glowBlur":0.45,"highlight":"#E7B45A","highlightStyle":"color","boxColor":null},
  {"id":"cap-ticker","name":"Ticker","category":"Education","popularity":88,"layout":"bottom","keyword":false,"font":"Oswald","fallbackFonts":["Bebas Neue","Inter","Arial"],"fontSize":54,"uppercase":true,"wordsPerCue":4,"anim":"karaoke","highlightScale":1.02,"fill":"#FFFFFF","stroke":"#000000","strokeWidth":5,"glow":null,"highlight":"#13C2A8","highlightStyle":"bar","boxOpacity":1},
  {"id":"cap-card","name":"Clean Card","category":"Minimal Professional","popularity":93,"layout":"bottom","keyword":false,"font":"Inter","fallbackFonts":["Helvetica","Arial"],"fontSize":52,"uppercase":false,"wordsPerCue":4,"anim":"karaoke","highlightScale":1,"upcomingOpacity":0.45,"fill":"#11151C","stroke":null,"strokeWidth":0,"glow":null,"highlight":"#2D7CFF","highlightStyle":"color","boxColor":"#FFFFFF","boxOpacity":0.96,"boxRadius":12},
  {"id":"cap-clean-sub","name":"Clean Subtitle","category":"Minimal Professional","popularity":96,"layout":"bottom","keyword":false,"font":"Inter","fallbackFonts":["Helvetica","Arial"],"fontSize":50,"uppercase":false,"wordsPerCue":5,"anim":"karaoke","highlightScale":1,"upcomingOpacity":1,"fill":"#8A93A3","stroke":null,"strokeWidth":0,"glow":null,"highlight":"#0B0F17","highlightStyle":"color","boxColor":"#FFFFFF","boxOpacity":1,"boxRadius":18},
  {"id":"cap-studio","name":"Studio","category":"Podcast Pro","popularity":90,"layout":"bottom","keyword":false,"font":"Manrope","fallbackFonts":["Inter","Arial"],"fontSize":54,"uppercase":false,"wordsPerCue":4,"anim":"karaoke","highlightScale":1.06,"upcomingOpacity":0.55,"fill":"#FFFFFF","stroke":null,"strokeWidth":0,"glow":"#000000","glowBlur":0.42,"highlight":"#FFC857","highlightStyle":"color","boxColor":null},
  {"id":"pro-boldpop","name":"Bold Pop","category":"⭐ Premium","popularity":100,"layout":"center","keyword":true,"font":"Archivo Black","fallbackFonts":["Montserrat","Poppins","Arial Black"],"fontSize":62,"weight":900,"uppercase":false,"wordsPerCue":6,"anim":"pop","highlightScale":1.5,"fill":"#FFFFFF","fill2":"#D2D7DE","glossy":true,"stroke":"#2A1A06","strokeWidth":5,"glow":"#000000","glowBlur":0.5,"highlight":"#FFE45C","highlight2":"#EF6C0A","highlightStyle":"color"},
  {"id":"pro-coolpop","name":"Cool Pop","category":"⭐ Premium","popularity":99,"layout":"center","keyword":true,"font":"Archivo Black","fallbackFonts":["Montserrat","Poppins","Arial Black"],"fontSize":62,"weight":900,"uppercase":false,"wordsPerCue":6,"anim":"pop","highlightScale":1.5,"fill":"#FFFFFF","fill2":"#D2D7DE","glossy":true,"stroke":"#06101A","strokeWidth":5,"glow":"#000000","glowBlur":0.5,"highlight":"#BFE3FF","highlight2":"#1E63E6","highlightStyle":"color"},
  {"id":"pro-cleanbold","name":"Clean Bold","category":"⭐ Premium","popularity":98,"layout":"center","keyword":true,"font":"Archivo Black","fallbackFonts":["Montserrat","Poppins","Arial Black"],"fontSize":62,"weight":900,"uppercase":false,"wordsPerCue":6,"anim":"pop","highlightScale":1.5,"fill":"#FFFFFF","fill2":"#CED2D8","stroke":null,"strokeWidth":0,"glow":"#000000","glowBlur":0.55,"highlight":"#FFFFFF","highlightStyle":"color","boxColor":null},
  {"id":"pro-editorial","name":"Editorial","category":"⭐ Premium","popularity":100,"layout":"center","keyword":true,"font":"Helvetica","fallbackFonts":["Arial","Inter","Montserrat"],"fontSize":60,"weight":700,"uppercase":false,"wordsPerCue":6,"anim":"pop","highlightScale":1.08,"fill":"#FFFFFF","fill2":"#DDE1E6","stroke":null,"strokeWidth":0,"glow":"#000000","glowBlur":0.6,"highlight":"#FFFFFF","highlightStyle":"color","highlightFont":"Playfair Display","highlightItalic":true,"boxColor":null},
  {"id":"btn-neon","name":"Neon","category":"🔘 Buttons","popularity":97,"layout":"center","keyword":false,"font":"Space Mono","fallbackFonts":["JetBrains Mono","Roboto Mono","monospace"],"fontSize":54,"weight":700,"uppercase":false,"wordsPerCue":3,"maxLines":1,"anim":"pop","highlightScale":1.06,"fill":"#14FF8E","glow":"#14FF8E","glowBlur":0.45,"highlight":"#A8FFD2","highlightStyle":"color","boxColor":"#0A0A0A","boxRadius":18,"boxPad":1.2,"boxStroke":"#14FF8E","boxStrokeWidth":4,"boxGlow":"#14FF8E","boxGlowBlur":0.8},
  {"id":"btn-spotify","name":"Spotify","category":"🔘 Buttons","popularity":95,"layout":"center","keyword":false,"font":"Inter","fallbackFonts":["Helvetica","Arial"],"fontSize":46,"weight":700,"uppercase":true,"wordsPerCue":3,"maxLines":1,"letterSpacing":3,"anim":"pop","highlightScale":1.05,"fill":"#FFFFFF","highlight":"#FFFFFF","highlightStyle":"color","boxColor":"#1DB954","boxRadius":120,"boxPad":1.4},
  {"id":"btn-pop3d","name":"Pop 3D","category":"🔘 Buttons","popularity":96,"layout":"center","keyword":false,"font":"Nunito","fallbackFonts":["Inter","Arial"],"fontSize":50,"weight":800,"uppercase":true,"wordsPerCue":3,"maxLines":1,"letterSpacing":1,"anim":"pop","highlightScale":1.06,"fill":"#FFFFFF","highlight":"#EAFFD0","highlightStyle":"color","boxColor":"#3FA000","boxRadius":120,"boxPad":1.35,"box3d":"#2C7000","box3dDepth":11},
  {"id":"btn-3dred","name":"3D Red","category":"🔘 Buttons","popularity":90,"layout":"center","keyword":false,"font":"Nunito","fallbackFonts":["Inter","Arial"],"fontSize":50,"weight":800,"wordsPerCue":3,"maxLines":1,"anim":"pop","highlightScale":1.06,"fill":"#7A1E1E","highlight":"#FFFFFF","highlightStyle":"color","boxColor":"#FF6666","boxRadius":120,"boxPad":1.35,"boxStroke":"#000000","boxStrokeWidth":3,"box3d":"#8B2626","box3dDepth":11},
  {"id":"btn-neo","name":"Neo","category":"🔘 Buttons","popularity":92,"layout":"center","keyword":false,"font":"Nunito","fallbackFonts":["Inter","Arial"],"fontSize":48,"weight":700,"wordsPerCue":3,"maxLines":1,"anim":"scale","highlightScale":1.04,"fill":"#6B4A33","highlight":"#3F2A1C","highlightStyle":"color","boxColor":"#F2C4A3","boxColor2":"#E5A878","boxGradient":"v","boxRadius":120,"boxPad":1.35,"boxShadow":"rgba(120,95,75,0.55)","boxShadowBlur":0.55,"boxShadowDY":9},
  {"id":"btn-aura","name":"Aura","category":"🔘 Buttons","popularity":94,"layout":"center","keyword":false,"font":"Inter","fallbackFonts":["Helvetica","Arial"],"fontSize":50,"weight":800,"wordsPerCue":3,"maxLines":1,"anim":"pop","highlightScale":1.05,"fill":"#111111","highlight":"#111111","highlightStyle":"color","boxColor":"#F4C5C1","boxGradient":"h","boxStops":[[0,"#FCF1B2"],[0.229,"#F4C5C1"],[0.406,"#EEC2EA"],[0.588,"#C0C8F9"],[0.75,"#C9F2FC"],[1,"#E7FCC5"]],"boxRadius":120,"boxPad":1.35,"boxStroke":"#000000","boxStrokeWidth":4},
  {"id":"btn-candy","name":"Candy","category":"🔘 Buttons","popularity":93,"layout":"center","keyword":false,"font":"Pacifico","fallbackFonts":["Caveat","Inter"],"fontSize":54,"weight":700,"wordsPerCue":2,"maxLines":1,"anim":"pop","highlightScale":1.06,"fill":"#FFFFFF","highlight":"#FFFFFF","highlightStyle":"color","boxColor":"#F75BA2","boxColor2":"#D73F6E","boxGradient":"v","boxRadius":120,"boxPad":1.35,"boxStroke":"#E0367E","boxStrokeWidth":2,"boxGloss":0.9},
  {"id":"btn-gold","name":"Gold Gloss","category":"🔘 Buttons","popularity":91,"layout":"center","keyword":false,"font":"Inter","fallbackFonts":["Helvetica","Arial"],"fontSize":50,"weight":800,"wordsPerCue":3,"maxLines":1,"anim":"pop","highlightScale":1.05,"fill":"#1B3661","highlight":"#1B3661","highlightStyle":"color","highlightItalic":true,"boxColor":"#F9BC5C","boxColor2":"#F9A92A","boxGradient":"v","boxRadius":120,"boxPad":1.35,"boxGloss":0.85},
  {"id":"btn-glass","name":"Glass","category":"🔘 Buttons","popularity":90,"layout":"center","keyword":false,"font":"Inter","fallbackFonts":["Helvetica","Arial"],"fontSize":50,"weight":700,"wordsPerCue":3,"maxLines":1,"anim":"scale","highlightScale":1.05,"fill":"#FFFFFF","highlight":"#FFFFFF","highlightStyle":"color","boxColor":"#15171C","boxOpacity":0.4,"boxRadius":120,"boxPad":1.35,"boxStroke":"#FFFFFF","boxStrokeWidth":2,"boxGlow":"#FFFFFF","boxGlowBlur":0.3},
  {"id":"btn-outline","name":"Outline","category":"🔘 Buttons","popularity":89,"layout":"center","keyword":false,"font":"Inter","fallbackFonts":["Helvetica","Arial"],"fontSize":50,"weight":800,"wordsPerCue":3,"maxLines":1,"anim":"pop","highlightScale":1.05,"fill":"#FFD23F","glow":"#000000","glowBlur":0.3,"highlight":"#FFFFFF","highlightStyle":"color","boxColor":null,"boxRadius":120,"boxPad":1.35,"boxStroke":"#FFD23F","boxStrokeWidth":4},
  {"id":"btn-pixel","name":"Pixel","category":"🔘 Buttons","popularity":88,"layout":"center","keyword":false,"font":"Space Mono","fallbackFonts":["Roboto Mono","Courier New","monospace"],"fontSize":46,"weight":700,"uppercase":true,"wordsPerCue":3,"maxLines":1,"anim":"pop","highlightScale":1.04,"fill":"#FFFFFF","highlight":"#7CF03F","highlightStyle":"color","boxColor":"#6B4423","boxRadius":2,"boxPad":1.25,"boxStroke":"#1C1208","boxStrokeWidth":6,"shadowDX":3,"shadowDY":3},
  {"id":"btn-blue","name":"Basic Blue","category":"🔘 Buttons","popularity":87,"layout":"center","keyword":false,"font":"Inter","fallbackFonts":["Helvetica","Arial"],"fontSize":48,"weight":700,"wordsPerCue":3,"maxLines":1,"anim":"pop","highlightScale":1.05,"fill":"#FFFFFF","highlight":"#FFFFFF","highlightStyle":"color","boxColor":"#4363F8","boxColor2":"#2748E1","boxGradient":"v","boxRadius":120,"boxPad":1.35},
  {"id":"btn-paper","name":"Paper","category":"🔘 Buttons","popularity":86,"layout":"center","keyword":false,"font":"Inter","fallbackFonts":["Helvetica","Arial"],"fontSize":48,"weight":800,"wordsPerCue":3,"maxLines":1,"anim":"scale","highlightScale":1.04,"fill":"#15171C","highlight":"#2D7CFF","highlightStyle":"color","boxColor":"#FFFFFF","boxRadius":120,"boxPad":1.35,"boxShadow":"rgba(0,0,0,0.35)","boxShadowBlur":0.45,"boxShadowDY":7},
  {"id":"btn-twitter","name":"Sky","category":"🔘 Buttons","popularity":85,"layout":"center","keyword":false,"font":"Inter","fallbackFonts":["Helvetica","Arial"],"fontSize":48,"weight":700,"wordsPerCue":3,"maxLines":1,"anim":"pop","highlightScale":1.05,"fill":"#FFFFFF","highlight":"#FFFFFF","highlightStyle":"color","boxColor":"#1BA1F2","boxRadius":120,"boxPad":1.35},
  {"id":"btn-twitch","name":"Purple","category":"🔘 Buttons","popularity":84,"layout":"center","keyword":false,"font":"Inter","fallbackFonts":["Helvetica","Arial"],"fontSize":48,"weight":800,"wordsPerCue":3,"maxLines":1,"anim":"pop","highlightScale":1.05,"fill":"#FFFFFF","highlight":"#E9DDFF","highlightStyle":"color","boxColor":"#9147FF","boxRadius":16,"boxPad":1.3},
  {"id":"btn-win","name":"Retro Win","category":"🔘 Buttons","popularity":83,"layout":"center","keyword":false,"font":"Inter","fallbackFonts":["Tahoma","Arial"],"fontSize":46,"weight":700,"wordsPerCue":3,"maxLines":1,"anim":"pop","highlightScale":1.04,"fill":"#111111","highlight":"#0A0AC8","highlightStyle":"color","boxColor":"#C8C8C8","boxRadius":3,"boxPad":1.25,"boxStroke":"#1A1A1A","boxStrokeWidth":2,"box3d":"#707070","box3dDepth":6,"boxGloss":0.35},
  {"id":"btn-bios","name":"BIOS","category":"🔘 Buttons","popularity":82,"layout":"center","keyword":false,"font":"Space Mono","fallbackFonts":["JetBrains Mono","Courier New","monospace"],"fontSize":44,"weight":700,"uppercase":true,"wordsPerCue":3,"maxLines":1,"anim":"pop","highlightScale":1.04,"fill":"#FFFFFF","highlight":"#5BFF8A","highlightStyle":"color","boxColor":"#0300E4","boxRadius":2,"boxPad":1.25,"boxStroke":"#6A78FF","boxStrokeWidth":2},
  {"id":"btn-figma","name":"Chip","category":"🔘 Buttons","popularity":84,"layout":"center","keyword":false,"font":"Inter","fallbackFonts":["Helvetica","Arial"],"fontSize":46,"weight":700,"wordsPerCue":3,"maxLines":1,"anim":"pop","highlightScale":1.05,"fill":"#FFFFFF","highlight":"#FFFFFF","highlightStyle":"color","boxColor":"#18A0FB","boxRadius":16,"boxPad":1.3},
  {"id":"btn-destijl","name":"De Stijl","category":"🔘 Buttons","popularity":83,"layout":"center","keyword":false,"font":"Archivo Black","fallbackFonts":["Inter","Arial"],"fontSize":46,"weight":800,"wordsPerCue":3,"maxLines":1,"anim":"pop","highlightScale":1.08,"fill":"#111111","highlight":"#E64043","highlightStyle":"color","boxColor":"#F1F1F1","boxRadius":2,"boxPad":1.3,"boxStroke":"#000000","boxStrokeWidth":7},
  {"id":"btn-google","name":"Slate","category":"🔘 Buttons","popularity":85,"layout":"center","keyword":false,"font":"Inter","fallbackFonts":["Roboto","Arial"],"fontSize":46,"weight":600,"wordsPerCue":3,"maxLines":1,"anim":"scale","highlightScale":1.04,"fill":"#FFFFFF","highlight":"#8AB4F8","highlightStyle":"color","boxColor":"#3D4043","boxRadius":26,"boxPad":1.3}
];

export const CATEGORY_ORDER: string[] = [
  "⭐ Premium", "Trending", "Bold Creator", "Dynamic Highlight", "Social Growth",
  "Minimal Professional", "Podcast Pro", "Storytelling", "Cinematic",
  "Gaming Stream", "Motivation", "Education", "🔘 Buttons",
];
